# Generated by Django 5.2.14 on 2026-05-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0274_secguard_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='affected_url',
            field=models.URLField(blank=True, default='', help_text='受影响URL', max_length=500),
        ),
        migrations.AddField(
            model_name='report',
            name='cve_id',
            field=models.CharField(blank=True, default='', help_text='CVE编号', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='reproduction_steps',
            field=models.TextField(blank=True, default='', help_text='复现步骤'),
        ),
    ]
