# Generated by Django 5.2.14 on 2026-05-08 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0275_add_report_extra_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='team',
            field=models.ForeignKey(blank=True, help_text='所属团队（数据隔离；系统日志可为空）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secguard_audit_logs', to='website.organization'),
        ),
        migrations.AddField(
            model_name='report',
            name='team',
            field=models.ForeignKey(blank=True, help_text='所属团队（数据隔离）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secguard_reports', to='website.organization'),
        ),
        migrations.AddField(
            model_name='scantask',
            name='team',
            field=models.ForeignKey(blank=True, help_text='所属团队（数据隔离）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secguard_scans', to='website.organization'),
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '团队管理员'), ('team_lead', '团队负责人'), ('developer', '开发人员'), ('observer', '观察者')], default='developer', help_text='用户在团队中的角色', max_length=20)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('accepted', '已通过'), ('rejected', '已拒绝')], default='pending', help_text='审核状态', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='加入时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='审核人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(help_text='类型为 team 的 Organization', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='website.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '团队成员',
                'verbose_name_plural': '团队成员',
                'indexes': [models.Index(fields=['team', 'status'], name='website_tea_team_id_d9871e_idx'), models.Index(fields=['user', 'status'], name='website_tea_user_id_f4232e_idx')],
                'unique_together': {('user', 'team')},
            },
        ),
    ]
