# Generated by Django 5.2.14 on 2026-05-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0276_add_team_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='findings_count',
            field=models.IntegerField(default=0, help_text='发现漏洞数量'),
        ),
    ]
