# Generated by Django 5.2.14 on 2026-05-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0277_add_findings_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='timeout_minutes',
            field=models.IntegerField(default=60, help_text='超时分钟数'),
        ),
        migrations.AddField(
            model_name='scantask',
            name='thread_count',
            field=models.IntegerField(default=10, help_text='每主机线程数 (-t)'),
        ),
        migrations.AddField(
            model_name='scantask',
            name='parallel_modules',
            field=models.IntegerField(default=5, help_text='并行模块数 (-M)'),
        ),
        migrations.AddField(
            model_name='scantask',
            name='hardware_usage',
            field=models.CharField(default='high', max_length=20, choices=[('low', '低'), ('normal', '正常'), ('high', '高'), ('maximum', '最大')], help_text='硬件使用级别'),
        ),
        migrations.AddField(
            model_name='scantask',
            name='selected_modules',
            field=models.TextField(blank=True, default='', help_text='自定义选择的模块，逗号分隔，空=全部'),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('host', '主机'), ('port', '端口'), ('service', '服务'), ('subdomain', '子域名'), ('web_tech', 'Web技术'), ('ssl_cert', 'SSL证书')], help_text='资产类型', max_length=20)),
                ('name', models.CharField(help_text='资产标识 (IP/域名/端口/服务名)', max_length=255)),
                ('value', models.TextField(blank=True, default='', help_text='详细信息 (JSON)')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('unknown', '未知')], default='online', help_text='在线状态', max_length=20)),
                ('target', models.CharField(help_text='所属扫描目标', max_length=255)),
                ('discovered_at', models.DateTimeField(auto_now_add=True, help_text='发现时间')),
                ('scan_task', models.ForeignKey(help_text='所属扫描任务', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='website.scantask')),
                ('team', models.ForeignKey(blank=True, help_text='所属团队（数据隔离）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secguard_assets', to='website.organization')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
                'ordering': ['-discovered_at'],
                'indexes': [
                    models.Index(fields=['asset_type'], name='asset_type_idx'),
                    models.Index(fields=['target'], name='asset_target_idx'),
                    models.Index(fields=['scan_task'], name='asset_scan_task_idx'),
                ],
            },
        ),
    ]
