import {
  Vulnerability,
  Asset,
  ScanTask,
  DashboardStats,
  VulnerabilityTrend,
  RecentVulnerability,
  TeamMember,
  AuditLog,
  ReportChart,
} from '@/types';
import {
  ShieldCheck,
  AlertTriangle,
  CheckCircle,
  Clock,
  Server,
} from 'lucide-react';
import {
  CheckCircle2,
  FileText,
  AlertTriangle as AlertIcon,
  Shield,
} from 'lucide-react';

export const mockVulnerabilities: Vulnerability[] = [
  {
    id: 'VUL-2024-0812',
    title: '核心鉴权组件拒绝服务漏洞 (RCE)',
    description: 'Asset auth-prod-v2-internal',
    severity: '关键',
    severityColor: 'bg-red-500',
    status: '待分派',
    statusColor: 'text-red-400',
    assignee: '张景瑞',
    date: '2024-05-18',
  },
  {
    id: 'VUL-2024-0810',
    title: 'SQL注入漏洞 - 用户查询接口',
    description: 'Asset api-gateway-prod',
    severity: '高',
    severityColor: 'bg-orange-500',
    status: '处理中',
    statusColor: 'text-yellow-400',
    assignee: '李明辉',
    date: '2024-05-17',
  },
  {
    id: 'VUL-2024-0808',
    title: 'XSS跨站脚本攻击 - 评论模块',
    description: 'Asset web-portal-public',
    severity: '高',
    severityColor: 'bg-orange-500',
    status: '已修复',
    statusColor: 'text-green-400',
    assignee: '王思琪',
    date: '2024-05-16',
  },
  {
    id: 'VUL-2024-0805',
    title: '敏感信息泄露 - 日志文件',
    description: 'Asset monitoring-dashboard',
    severity: '中',
    severityColor: 'bg-yellow-500',
    status: '处理中',
    statusColor: 'text-yellow-400',
    assignee: '赵晓峰',
    date: '2024-05-15',
  },
  {
    id: 'VUL-2024-0803',
    title: 'CSRF跨站请求伪造 - 表单提交',
    description: 'Asset mobile-app-backend',
    severity: '中',
    severityColor: 'bg-yellow-500',
    status: '待分派',
    statusColor: 'text-red-400',
    assignee: '陈雨婷',
    date: '2024-05-14',
  },
];

export const mockAssets: Asset[] = [
  {
    id: 'AST-001',
    name: 'auth-prod-v2-internal',
    type: '服务器',
    icon: null,
    ip: '192.168.1.100',
    status: '在线',
    statusColor: 'text-green-400',
    vulnerabilities: 3,
    lastScan: '2024-05-18',
    criticality: '高',
    criticalityColor: 'bg-red-500/20 text-red-400 border-red-500/30',
  },
  {
    id: 'AST-002',
    name: 'web-portal-public',
    type: 'Web应用',
    icon: null,
    url: 'https://portal.example.com',
    status: '在线',
    statusColor: 'text-green-400',
    vulnerabilities: 7,
    lastScan: '2024-05-17',
    criticality: '关键',
    criticalityColor: 'bg-red-500/20 text-red-400 border-red-500/30',
  },
  {
    id: 'AST-003',
    name: 'db-master-cluster',
    type: '数据库',
    icon: null,
    ip: '10.0.0.50',
    status: '在线',
    statusColor: 'text-green-400',
    vulnerabilities: 2,
    lastScan: '2024-05-16',
    criticality: '高',
    criticalityColor: 'bg-red-500/20 text-red-400 border-red-500/30',
  },
  {
    id: 'AST-004',
    name: 'api-gateway-prod',
    type: 'API服务',
    icon: null,
    url: 'https://api.example.com',
    status: '警告',
    statusColor: 'text-yellow-400',
    vulnerabilities: 12,
    lastScan: '2024-05-15',
    criticality: '关键',
    criticalityColor: 'bg-red-500/20 text-red-400 border-red-500/30',
  },
  {
    id: 'AST-005',
    name: 'monitoring-dashboard',
    type: 'Web应用',
    icon: null,
    url: 'https://monitor.example.com',
    status: '离线',
    statusColor: 'text-red-400',
    vulnerabilities: 0,
    lastScan: '2024-05-10',
    criticality: '中',
    criticalityColor: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30',
  },
  {
    id: 'AST-006',
    name: 'mobile-app-backend',
    type: 'API服务',
    icon: null,
    url: 'https://mapi.example.com',
    status: '在线',
    statusColor: 'text-green-400',
    vulnerabilities: 5,
    lastScan: '2024-05-14',
    criticality: '中',
    criticalityColor: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30',
  },
];

export const mockScanTasks: ScanTask[] = [
  {
    id: 'SC-0821',
    name: 'Main_Portal_Daily',
    url: 'https://api.internal.com',
    status: '运行中',
    statusColor: 'text-cyan-400',
    progress: 64,
    findings: 14,
    lastRun: '2023-11-24 10:30',
  },
  {
    id: 'SC-0620',
    name: 'CRM_System_Deep',
    url: 'https://crm.secguard.io',
    status: '已排队',
    statusColor: 'text-yellow-400',
    progress: 0,
    findings: '--',
    lastRun: '待执行',
  },
  {
    id: 'SC-0409',
    name: 'Auth_Module_Sprint',
    url: 'https://auth.secguard.io',
    status: '已完成',
    statusColor: 'text-green-400',
    progress: 100,
    findings: 31,
    lastRun: '2023-11-23 22:15',
  },
];

export const mockDashboardStats: DashboardStats[] = [
  {
    title: '漏洞总数',
    value: '1,284',
    icon: ShieldCheck,
    change: '+12.5%',
    color: 'text-primary',
    bgColor: 'bg-primary/10',
  },
  {
    title: '待修复',
    value: '342',
    icon: AlertTriangle,
    change: '高风险',
    color: 'text-red-500',
    bgColor: 'bg-red-500/10',
  },
  {
    title: '已修复',
    value: '942',
    icon: CheckCircle,
    change: '',
    color: 'text-green-500',
    bgColor: 'bg-green-500/10',
  },
  {
    title: '平均修复时长',
    value: '4.2',
    unit: 'Days',
    icon: Clock,
    change: '',
    color: 'text-yellow-500',
    bgColor: 'bg-yellow-500/10',
  },
];

export const mockVulnerabilityData: VulnerabilityTrend[] = [
  { name: '极危险 (Critical)', value: 12, color: '#ef4444' },
  { name: '高危 (High)', value: 28, color: '#f97316' },
  { name: '中危 (Medium)', value: 45, color: '#eab308' },
  { name: '低危 (Low)', value: 15, color: '#22c55e' },
];

export const mockTrendData: VulnerabilityTrend[] = [
  { name: 'MON', value: 30 },
  { name: 'TUE', value: 45 },
  { name: 'WED', value: 35 },
  { name: 'THU', value: 65 },
  { name: 'FRI', value: 85 },
  { name: 'SAT', value: 70 },
  { name: 'SUN', value: 55 },
];

export const mockRecentVulnerabilities: RecentVulnerability[] = [
  {
    id: 'CVE-2024-3812',
    title: '核心网关权限提升漏洞 (RCE)',
    severity: 'CRITICAL',
    severityColor: 'bg-red-500',
    assignee: '张景瑞',
    date: '2024-05-18',
  },
  {
    id: 'CVE-2023-4512',
    title: 'SQL注入漏洞导致敏感数据泄露',
    severity: 'HIGH RISK',
    severityColor: 'bg-orange-500',
    assignee: '李伟',
    date: '2024-05-17',
  },
  {
    id: 'CVE-2024-1102',
    title: '跨站脚本攻击 (XSS) 风险',
    severity: 'MEDIUM',
    severityColor: 'bg-yellow-500',
    assignee: '孔凡',
    date: '2024-05-10',
  },
];

export const mockTeamMembers: TeamMember[] = [
  {
    id: 1,
    name: 'Chen.Wei',
    email: 'wei.chen@secguard.io',
    role: '管理员',
    roleColor: 'bg-primary/10 text-primary',
    lastActive: '最后活跃: 2分钟前',
    avatar: 'C',
  },
  {
    id: 2,
    name: 'Li.Jianhua',
    email: 'jianhua@secguard.io',
    role: '安全专家',
    roleColor: 'bg-cyan-500/10 text-cyan-400',
    lastActive: '最后活跃: 5小时前',
    avatar: 'L',
  },
  {
    id: 3,
    name: 'Zhang.Min',
    email: 'min.zhang@dev.internal',
    role: '开发人员',
    roleColor: 'bg-green-500/10 text-green-400',
    lastActive: '最后活跃: 昨天',
    avatar: 'Z',
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    user: 'Chen.Wei',
    action: '更新节点防火墙策略',
    ip: '192.168.1.164',
    time: '2023-10-27 14:22:10',
    icon: CheckCircle2,
    iconColor: 'text-blue-500',
  },
  {
    user: 'Li.Jianhua',
    action: '导出漏洞扫描报告 #842',
    ip: '10.0.42.12',
    time: '2023-10-27 13:05:44',
    icon: FileText,
    iconColor: 'text-blue-500',
  },
  {
    user: 'System',
    action: '异常登录重试拦截',
    ip: '213.44.11.2',
    time: '2023-10-27 12:40:02',
    icon: AlertIcon,
    iconColor: 'text-red-500',
  },
  {
    user: 'Zhang.Min',
    action: '重置 API Access Token',
    ip: '192.168.1.156',
    time: '2023-10-27 11:15:29',
    icon: Shield,
    iconColor: 'text-blue-500',
  },
];

export const mockReportChartData: ReportChart[] = [
  { name: 'W1', value: 65 },
  { name: 'W2', value: 48 },
  { name: 'W3', value: 85 },
  { name: 'W4', value: 72 },
];
